# Generated by Django 5.0.6 on 2024-06-12 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_auto_20200508_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='contacto',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='expense',
            name='ddespacho',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='expense',
            name='dfactura',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='expense',
            name='ncompra',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
